import news1 from "../assets/news1.jpg";
import news2 from "../assets/news2.jpg";
import news3 from "../assets/news3.jpg";

export const latestNews = [
  {
    id: 1,
    image: news1,
    day: "18",
    month: "NOV",
    category: "Food",
    author: "User",
    comments: 66,
    title: "Curabitur porttitor orci eget neque accumsan venenatis. Nunc fermentum.",
    button: "Read More",
  },
  {
    id: 2,
    image: news2,
    day: "29",
    month: "JAN",
    category: "Food",
    author: "Admin",
    comments: 165,
    title: "Eget lobortis lorem lacinia. Vivamus pharetra semper.",
    button: "Read More",
  },
  {
    id: 3,
    image: news3,
    day: "21",
    month: "FEB",
    category: "Food",
    author: "Admin",
    comments: 75,
    title: "Maecenas blandit risus elementum mauris malesuada.",
    button: "Read More",
  },
  {
    id: 4,
    image: news3,
    day: "21",
    month: "FEB",
    category: "Food",
    author: "Admin",
    comments: 65,
    title: "Maecenas blandit risus elementum mauris malesuada.",
    button: "Read More",
  },
  {
    id: 5,
    image: news3,
    day: "21",
    month: "FEB",
    category: "Food",
    author: "Admin",
    comments: 75,
    title: "Maecenas blandit risus elementum mauris malesuada.",
    button: "Read More",
  },
  {
    id: 6,
    image: news3,
    day: "21",
    month: "FEB",
    category: "Food",
    author: "Admin",
    comments: 65,
    title: "Maecenas blandit risus elementum mauris malesuada.",
    button: "Read More",
  },
  {
    id: 7,
    image: news3,
    day: "21",
    month: "FEB",
    category: "Food",
    author: "Admin",
    comments: 65,
    title: "Maecenas blandit risus elementum mauris malesuada.",
    button: "Read More",
  },
  {
    id: 8,
    image: news3,
    day: "21",
    month: "FEB",
    category: "Food",
    author: "Admin",
    comments: 65,
    title: "Maecenas blandit risus elementum mauris malesuada.",
    button: "Read More",
  },
  {
    id: 9,
    image: news3,
    day: "21",
    month: "FEB",
    category: "Food",
    author: "Admin",
    comments: 75,
    title: "Maecenas blandit risus elementum mauris malesuada.",
    button: "Read More",
  },
  
];

export default latestNews;